### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by H1ghSp4rr0w** [Quaggles/dcs-input-command-injector#4]
Hi man thanks for a great mod.
Is it possible to make the mini-stick on the X56 a hat switch or 4 buttons? I would really like to mod it to counter measure as in real aircraft im flying. I know i can do it in the Logitech software but i cant stand it because it's messing with every input on my computer.

Have a nice weekend!!!

**Comment by Quaggles** [comment]
Unfortunately it's not possible to map an analog input to digital inside DCS even with this mod. I've run into the same issue wanting to bind the X-55 rotary on the throttle to the radar elevation keys on the Mirage F1 since it doesn't accept an axis binding.

The best solution I've found is to use [AutoHotkey](https://www.autohotkey.com/) to create a script that presses virtual keyboard keys that aren't used by Windows, for example the following keys don't do anything in Windows but you can bind them in DCS:
```
Launch_Mail
Launch_Media
Launch_App1
Launch_App2
```
https://www.autohotkey.com/docs/v1/KeyList.htm

![image](https://user-images.githubusercontent.com/8382945/216919263-dea6a3dc-6350-4789-bc5f-b9c0bbb922a0.png)

Here is the script I use as a starting point [DCS-Elevation-Axis-To-Button.zip](https://github.com/Quaggles/dcs-input-command-injector/files/10660976/DCS-Elevation-Axis-To-Button.zip)

It only sends keys while DCS is the focused window and it maps 1 axis to 2 buttons, you'll need to find out your controller/axis ID's with [this tool](https://www.autohotkey.com/docs/v1/scripts/index.htm#JoystickTest) and subsitute them into the script, then extend it so it works the same but with a second axis, or run the script twice with 2 sets of axis/keys.
