### ISSUE TITLE
Hardlinking

### ISSUE THREAD

**Issue by speedbird5** [Quaggles/dcs-input-command-injector#5]
Hi Quaggles, thanks for this mod.

I tested the hardlinking idea by just copying my saved games A10C2 joystick default.lua into the keyboard folder but when I start DCS I get a blank controls menu.

I think this results because the saved games joystick default.lua has axis commands in it and the keyboard default.lua does not normally have them.

When I deleted the axis commands from the joystick default.lua , then it worked.

Maybe add this as a note under the Hardlinking section ?

**Comment by Quaggles** [comment]
Good find, the injector would always try to join tables but for keyboard calls the axisCommands table was nil instead of empty so would fail.

I've written a workaround that does 2 things:
1. If the original table is nil it doesn't attempt a join and instead just sets it directly, this solves the issue and might catch some other errors that could happen.
2. It will skip doing anything with the axisCommands table when the device triggering the call is "Keyboard", this prevents axis binds from showing up in the keyboard column since they would be unusable anyway.

That seems to have resolved the issue so you can still hardlink them. I've attached a new version of the mod, can you verify it solves the issue for you? If it does I'll push it as a new version.

[DCS-Input-Command-Injector-Quaggles.zip](https://github.com/Quaggles/dcs-input-command-injector/files/11361615/DCS-Input-Command-Injector-Quaggles.zip)

**Comment by speedbird5** [comment]
Thanks. I will try the new version out tomorrow for you. Will get back to you.

**Comment by speedbird5** [comment]
New version tested and all working now.  Thanks
